// <auto-generated/>
#nullable restore

using System;
using System.Linq;
using System.Linq.Expressions;

namespace AlephMapper.Tests;

[global::System.CodeDom.Compiler.GeneratedCode("AlephMapper", "0.7.2.0")]
partial class ReferenceTypeOnlyMapper
{
    /// <summary>
    /// This is an auto-generated expression companion for <see cref="MapToDestination(global::AlephMapper.Tests.ReferenceTypeOnlySource)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are ignored and treated as regular member access.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.ReferenceTypeOnlySource, global::AlephMapper.Tests.ReferenceTypeOnlyDestination>> MapToDestinationExpression() =>
        source => new global::AlephMapper.Tests.ReferenceTypeOnlyDestination
        {
            StringProperty = source.StringProperty,
            ObjectProperty = source.ObjectProperty != null
                ? new global::AlephMapper.Tests.SimpleReferenceObject
                {
                    Name = source.ObjectProperty.Name
                }
                : null
        };

    /// <summary>
    /// This is an auto-generated update method for <see cref="MapToDestination(global::AlephMapper.Tests.ReferenceTypeOnlySource)"/>.
    /// </summary>
    /// <param name="source">The source object to map values from. If null, no updates are performed.</param>
    /// <param name="dest">The destination object to update. If null, the new instance is created.</param>
    /// <returns>The updated destination object for method chaining, or the new destination instance if either parameter is null.</returns>
    public static global::AlephMapper.Tests.ReferenceTypeOnlyDestination MapToDestination(global::AlephMapper.Tests.ReferenceTypeOnlySource source, global::AlephMapper.Tests.ReferenceTypeOnlyDestination dest)
    {
        if (source == null) return dest;
        if (dest == null)
            dest = new global::AlephMapper.Tests.ReferenceTypeOnlyDestination();
        dest.StringProperty = source.StringProperty;
        if (source.ObjectProperty != null)
        {
            if (dest.ObjectProperty == null)
                dest.ObjectProperty = new global::AlephMapper.Tests.SimpleReferenceObject();
            dest.ObjectProperty.Name = source.ObjectProperty.Name;
        }
        else
        {
            dest.ObjectProperty = null;
        }
        return dest;
    }
}
