// <auto-generated/>

using System;
using System.Linq;
using System.Linq.Expressions;

namespace AlephMapper.Tests;

[global::System.CodeDom.Compiler.GeneratedCode("AlephMapper", "0.7.0.0")]
partial class ComplexValueTypeMapper
{
#nullable disable
    /// <summary>
    /// This is an auto-generated expression companion for <see cref="MapToDestination(global::AlephMapper.Tests.ComplexValueTypeSource)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are ignored and treated as regular member access.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.ComplexValueTypeSource, global::AlephMapper.Tests.ComplexValueTypeDestination>> MapToDestinationExpression() =>
        source => new global::AlephMapper.Tests.ComplexValueTypeDestination
        {
            Id = source.Id,
            Name = source.Name,
            Address = new global::AlephMapper.Tests.AddressStruct
            {
                Street = source.Address.Street,
                City = source.Address.City,
                ZipCode = source.Address.ZipCode,
                Coordinates = new global::AlephMapper.Tests.CoordinatesStruct
                {
                    Latitude = source.Address.Coordinates.Latitude,
                    Longitude = source.Address.Coordinates.Longitude,
                    Elevation = source.Address.Coordinates.Elevation
                }
            },
            ContactInfo = new global::AlephMapper.Tests.ContactInfoStruct
            {
                Email = source.ContactInfo.Email,
                Phone = source.ContactInfo.Phone,
                PreferredMethod = source.ContactInfo.PreferredMethod,
                EmergencyContact = new global::AlephMapper.Tests.EmergencyContactStruct
                {
                    Name = source.ContactInfo.EmergencyContact.Name,
                    Relationship = source.ContactInfo.EmergencyContact.Relationship,
                    Phone = source.ContactInfo.EmergencyContact.Phone
                }
            },
            Metadata = new global::AlephMapper.Tests.MetadataStruct
            {
                CreatedAt = source.Metadata.CreatedAt,
                UpdatedAt = source.Metadata.UpdatedAt,
                Version = source.Metadata.Version,
                Tags = new global::AlephMapper.Tests.TagsStruct
                {
                    Primary = source.Metadata.Tags.Primary,
                    Secondary = source.Metadata.Tags.Secondary,
                    Category = source.Metadata.Tags.Category
                }
            }
        };
#nullable restore
}
