// <auto-generated/>
#nullable enable

using System;
using System.Linq;
using System.Linq.Expressions;

namespace AlephMapper.Tests;

[global::System.CodeDom.Compiler.GeneratedCode("AlephMapper", "0.7.0.0")]
partial class SimpleValueToReferenceMapper
{
    /// <summary>
    /// This is an auto-generated expression companion for <see cref="Map(global::AlephMapper.Tests.SimpleValueTypeSource)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are ignored and treated as regular member access.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.SimpleValueTypeSource, global::AlephMapper.Tests.SimpleReferenceTypeDestination>> MapExpression() =>
        source => new global::AlephMapper.Tests.SimpleReferenceTypeDestination
        {
            Value = source.Value,
            Name = source.Name
        };

    /// <summary>
    /// This is an auto-generated update method for <see cref="Map(global::AlephMapper.Tests.SimpleValueTypeSource)"/>.
    /// </summary>
    /// <param name="source">The source object to map values from. If null, no updates are performed.</param>
    /// <param name="dest">The destination object to update. If null, the new instance is created.</param>
    /// <returns>The updated destination object for method chaining, or the new destination instance if either parameter is null.</returns>
    public static global::AlephMapper.Tests.SimpleReferenceTypeDestination Map(global::AlephMapper.Tests.SimpleValueTypeSource source, global::AlephMapper.Tests.SimpleReferenceTypeDestination dest)
    {
        if (dest == null)
            dest = new global::AlephMapper.Tests.SimpleReferenceTypeDestination();
        dest.Value = source.Value;
        dest.Name = source.Name;
        return dest;
    }
}
