// <auto-generated/>
#nullable enable

using System;
using System.CodeDom.Compiler;
using System.Linq;
using System.Linq.Expressions;

namespace AlephMapper.Tests;

[GeneratedCode("AlephMapper", "0.7.0")]
partial class ValueTypeMapper
{
}
