// <auto-generated/>
#nullable restore

using System;
using System.Linq;
using System.Linq.Expressions;

namespace AlephMapper.Tests;

[global::System.CodeDom.Compiler.GeneratedCode("AlephMapper", "0.7.2.0")]
partial class ValueTypeMapper
{
}
