// <auto-generated/>
#nullable enable

using System;
using System.Linq;
using System.Linq.Expressions;

namespace AlephMapper.Tests;

[global::System.CodeDom.Compiler.GeneratedCode("AlephMapper", "0.7.0.0")]
partial class ValueToReferenceMapper
{
    /// <summary>
    /// This is an auto-generated expression companion for <see cref="MapToReferenceDestination(global::AlephMapper.Tests.ComplexValueTypeSource)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are ignored and treated as regular member access.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.ComplexValueTypeSource, global::AlephMapper.Tests.ComplexReferenceTypeDestination>> MapToReferenceDestinationExpression() =>
        source => new global::AlephMapper.Tests.ComplexReferenceTypeDestination
        {
            Id = source.Id,
            Name = source.Name,
            Address = new global::AlephMapper.Tests.AddressClass
            {
                Street = source.Address.Street,
                City = source.Address.City,
                ZipCode = source.Address.ZipCode,
                Coordinates = new global::AlephMapper.Tests.CoordinatesClass
                {
                    Latitude = source.Address.Coordinates.Latitude,
                    Longitude = source.Address.Coordinates.Longitude,
                    Elevation = source.Address.Coordinates.Elevation
                }
            },
            ContactInfo = new global::AlephMapper.Tests.ContactInfoClass
            {
                Email = source.ContactInfo.Email,
                Phone = source.ContactInfo.Phone,
                PreferredMethod = source.ContactInfo.PreferredMethod,
                EmergencyContact = new global::AlephMapper.Tests.EmergencyContactClass
                {
                    Name = source.ContactInfo.EmergencyContact.Name,
                    Relationship = source.ContactInfo.EmergencyContact.Relationship,
                    Phone = source.ContactInfo.EmergencyContact.Phone
                }
            },
            Metadata = new global::AlephMapper.Tests.MetadataClass
            {
                CreatedAt = source.Metadata.CreatedAt,
                UpdatedAt = source.Metadata.UpdatedAt,
                Version = source.Metadata.Version,
                Tags = new global::AlephMapper.Tests.TagsClass
                {
                    Primary = source.Metadata.Tags.Primary,
                    Secondary = source.Metadata.Tags.Secondary,
                    Category = source.Metadata.Tags.Category
                }
            }
        };

    /// <summary>
    /// This is an auto-generated update method for <see cref="MapToReferenceDestination(global::AlephMapper.Tests.ComplexValueTypeSource)"/>.
    /// </summary>
    /// <param name="source">The source object to map values from. If null, no updates are performed.</param>
    /// <param name="dest">The destination object to update. If null, the new instance is created.</param>
    /// <returns>The updated destination object for method chaining, or the new destination instance if either parameter is null.</returns>
    public static global::AlephMapper.Tests.ComplexReferenceTypeDestination MapToReferenceDestination(global::AlephMapper.Tests.ComplexValueTypeSource source, global::AlephMapper.Tests.ComplexReferenceTypeDestination dest)
    {
        if (dest == null)
            dest = new global::AlephMapper.Tests.ComplexReferenceTypeDestination();
        dest.Id = source.Id;
        dest.Name = source.Name;
        if (dest.Address == null)
            dest.Address = new global::AlephMapper.Tests.AddressClass();
        dest.Address.Street = source.Address.Street;
        dest.Address.City = source.Address.City;
        dest.Address.ZipCode = source.Address.ZipCode;
        if (dest.Address.Coordinates == null)
            dest.Address.Coordinates = new global::AlephMapper.Tests.CoordinatesClass();
        dest.Address.Coordinates.Latitude = source.Address.Coordinates.Latitude;
        dest.Address.Coordinates.Longitude = source.Address.Coordinates.Longitude;
        dest.Address.Coordinates.Elevation = source.Address.Coordinates.Elevation;
        if (dest.ContactInfo == null)
            dest.ContactInfo = new global::AlephMapper.Tests.ContactInfoClass();
        dest.ContactInfo.Email = source.ContactInfo.Email;
        dest.ContactInfo.Phone = source.ContactInfo.Phone;
        dest.ContactInfo.PreferredMethod = source.ContactInfo.PreferredMethod;
        if (dest.ContactInfo.EmergencyContact == null)
            dest.ContactInfo.EmergencyContact = new global::AlephMapper.Tests.EmergencyContactClass();
        dest.ContactInfo.EmergencyContact.Name = source.ContactInfo.EmergencyContact.Name;
        dest.ContactInfo.EmergencyContact.Relationship = source.ContactInfo.EmergencyContact.Relationship;
        dest.ContactInfo.EmergencyContact.Phone = source.ContactInfo.EmergencyContact.Phone;
        if (dest.Metadata == null)
            dest.Metadata = new global::AlephMapper.Tests.MetadataClass();
        dest.Metadata.CreatedAt = source.Metadata.CreatedAt;
        dest.Metadata.UpdatedAt = source.Metadata.UpdatedAt;
        dest.Metadata.Version = source.Metadata.Version;
        if (dest.Metadata.Tags == null)
            dest.Metadata.Tags = new global::AlephMapper.Tests.TagsClass();
        dest.Metadata.Tags.Primary = source.Metadata.Tags.Primary;
        dest.Metadata.Tags.Secondary = source.Metadata.Tags.Secondary;
        dest.Metadata.Tags.Category = source.Metadata.Tags.Category;
        return dest;
    }
}
