// <auto-generated/>
#nullable restore

using AgileObjects.ReadableExpressions;
using System;
using System.Linq;
using System.Linq.Expressions;

namespace AlephMapper.Tests;

[global::System.CodeDom.Compiler.GeneratedCode("AlephMapper", "0.7.2.0")]
partial class NestedExt_PersonMapper_Ignore
{
    /// <summary>
    /// This is an auto-generated expression companion for <see cref="ToDto(global::AlephMapper.Tests.NestedExt_Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are ignored and treated as regular member access.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.NestedExt_Person, global::AlephMapper.Tests.NestedExt_PersonDto>> ToDtoExpression() =>
        p => new global::AlephMapper.Tests.NestedExt_PersonDto
        {
            HomeAddress = new global::AlephMapper.Tests.NestedExt_AddressDto
            {
                Street = p.Friend.HomeAddress.Street,
                City = p.Friend.HomeAddress.City
            }
        };
}
