// <auto-generated/>

using AgileObjects.ReadableExpressions;
using System;
using System.Linq;
using System.Linq.Expressions;

namespace AlephMapper.Tests;

[global::System.CodeDom.Compiler.GeneratedCode("AlephMapper", "0.7.0.0")]
partial class NestedExt_AddressMapper
{
#nullable disable
    /// <summary>
    /// This is an auto-generated expression companion for <see cref="ToDto(global::AlephMapper.Tests.NestedExt_Address)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are ignored and treated as regular member access.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.NestedExt_Address, global::AlephMapper.Tests.NestedExt_AddressDto>> ToDtoExpression() =>
        a => new global::AlephMapper.Tests.NestedExt_AddressDto
        {
            Street = a.Street,
            City = a.City
        };
#nullable restore
}
