// <auto-generated/>
#nullable enable

using AlephMapper;
using System;
using System.Linq;
using System.Linq.Expressions;

namespace AlephMapper.Tests.MultiParameterInlining;

[global::System.CodeDom.Compiler.GeneratedCode("AlephMapper", "0.7.0.0")]
partial class UpdatableMultiParamMapper
{
    /// <summary>
    /// This is an auto-generated expression companion for <see cref="ToDto(global::AlephMapper.Tests.MultiParameterInlining.Person, int)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are ignored and treated as regular member access.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.MultiParameterInlining.Person, global::AlephMapper.Tests.MultiParameterInlining.PersonDto>> ToDtoExpression(int currentYear) =>
        person => new global::AlephMapper.Tests.MultiParameterInlining.PersonDto
        {
            FullName = person.First + " " + person.Last,
            BirthYear = currentYear - person.Age
        };

    /// <summary>
    /// This is an auto-generated update method for <see cref="ToDto(global::AlephMapper.Tests.MultiParameterInlining.Person, int)"/>.
    /// </summary>
    /// <param name="person">The source object to map values from. If null, no updates are performed.</param>
    /// <param name="currentYear"/>
    /// <param name="dest">The destination object to update. If null, the new instance is created.</param>
    /// <returns>The updated destination object for method chaining, or the new destination instance if either parameter is null.</returns>
    public static global::AlephMapper.Tests.MultiParameterInlining.PersonDto ToDto(global::AlephMapper.Tests.MultiParameterInlining.Person person, int currentYear, global::AlephMapper.Tests.MultiParameterInlining.PersonDto dest)
    {
        if (person == null) return dest;
        if (dest == null)
            dest = new global::AlephMapper.Tests.MultiParameterInlining.PersonDto();
        dest.FullName = person.First + " " + person.Last;
        dest.BirthYear = currentYear - person.Age;
        return dest;
    }
}
