// <auto-generated/>
#nullable enable

using AlephMapper;
using System;
using System.Linq;
using System.Linq.Expressions;

namespace Tests;

[global::System.CodeDom.Compiler.GeneratedCode("AlephMapper", "0.7.0.0")]
partial class PersonMapper
{
    /// <summary>
    /// This is an auto-generated adapted mapping method for <see cref="MapPerson(global::Tests.Person, bool)"/>.
    /// </summary>
    public static global::Tests.EmployeeDto MapEmployee(global::Tests.Employee source, bool includeEmail) =>
        includeEmail
            ? new global::Tests.EmployeeDto
            {
                Id = source.Id,
                Name = source.FirstName + " " + source.LastName,
                Email = source.Email
            }
            : new global::Tests.EmployeeDto
            {
                Id = source.Id,
                Name = source.FirstName + " " + source.LastName,
                Email = string.Empty
            };

    /// <summary>
    /// This is an auto-generated adapted expression companion for <see cref="MapPerson(global::Tests.Person, bool)"/>.
    /// </summary>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::Tests.Employee, global::Tests.EmployeeDto>> MapEmployeeExpression(bool includeEmail) =>
        source => includeEmail
            ? new global::Tests.EmployeeDto
            {
                Id = source.Id,
                Name = source.FirstName + " " + source.LastName,
                Email = source.Email
            }
            : new global::Tests.EmployeeDto
            {
                Id = source.Id,
                Name = source.FirstName + " " + source.LastName,
                Email = string.Empty
            };

    /// <summary>
    /// This is an auto-generated adapted expression companion for <see cref="MapPersonWithDetail(global::Tests.PersonWithDetail, string)"/>.
    /// </summary>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::Tests.EmployeeWithDetail, global::Tests.EmployeeWithDetailDto>> MapEmployeeWithDetailExpression(string userLanguageCode) =>
        source => new global::Tests.EmployeeWithDetailDto
        {
            Id = source.Id,
            Details = source.Details
                .Select(detail => new global::Tests.DetailDto
                {
                    Code = detail.Code,
                    Description = detail.Descriptions
                        .Where(description => description.LanguageCode == userLanguageCode)
                        .Select(description => description.Text)
                        .FirstOrDefault() ?? detail.Code
                })
                .ToList()
        };
}
