// <auto-generated/>
#nullable restore

using AlephMapper;
using System;
using System.Linq;
using System.Linq.Expressions;

namespace AlephMapper.Tests.MultiParamExtensionInlining;

[global::System.CodeDom.Compiler.GeneratedCode("AlephMapper", "0.7.1.0")]
partial class PersonProductMapperIgnore
{
    /// <summary>
    /// This is an auto-generated expression companion for <see cref="ToDto(global::AlephMapper.Tests.MultiParamExtensionInlining.Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are ignored and treated as regular member access.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.MultiParamExtensionInlining.Person, global::AlephMapper.Tests.MultiParamExtensionInlining.PersonProductDto>> ToDtoExpression() =>
        person => new global::AlephMapper.Tests.MultiParamExtensionInlining.PersonProductDto
        {
            Name = person.Name,
            FavoritePrice = "$" + person.FavoriteProduct.Price
        };
}
