// <auto-generated/>
#nullable restore

using System;
using System.Linq;
using System.Linq.Expressions;

namespace AlephMapper.Tests;

[global::System.CodeDom.Compiler.GeneratedCode("AlephMapper", "0.7.1.0")]
partial class Address1Mapper
{
    /// <summary>
    /// This is an auto-generated expression companion for <see cref="MapToDto(global::AlephMapper.Tests.Address1)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are ignored and treated as regular member access.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.Address1, global::AlephMapper.Tests.Address1Dto>> MapToDtoExpression() =>
        sourceAddress => new global::AlephMapper.Tests.Address1Dto
        {
            Line1 = sourceAddress.Line1 == null
                ? null
                : new global::AlephMapper.Tests.AddressLineDto
                {
                    Street = sourceAddress.Line1.Street,
                    HouseNumber = sourceAddress.Line1.HouseNumber
                },
            Line2 = sourceAddress.Line2 == null
                ? null
                : new global::AlephMapper.Tests.AddressLineDto
                {
                    Street = sourceAddress.Line2.Street,
                    HouseNumber = sourceAddress.Line2.HouseNumber
                }
        };
}
