// <auto-generated/>

using System;
using System.Linq;
using System.Linq.Expressions;

namespace AlephMapper.Tests;

[global::System.CodeDom.Compiler.GeneratedCode("AlephMapper", "0.7.0.0")]
partial class CircularPropertyMapper
{
#nullable disable
    /// <summary>
    /// This is an auto-generated expression companion for <see cref="UpdateTypeA(global::AlephMapper.Tests.CircularPropsSource)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are ignored and treated as regular member access.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.CircularPropsSource, global::AlephMapper.Tests.TypeA>> UpdateTypeAExpression() =>
        source => new global::AlephMapper.Tests.TypeA
        {
            Name = source.Name,
            B = new global::AlephMapper.Tests.TypeB
            {
                A = new global::AlephMapper.Tests.TypeA
                {
                    Name = source.Name
                }
            }
        };
#nullable restore

#nullable disable
    /// <summary>
    /// This is an auto-generated update method for <see cref="UpdateTypeA(global::AlephMapper.Tests.CircularPropsSource)"/>.
    /// </summary>
    /// <param name="source">The source object to map values from. If null, no updates are performed.</param>
    /// <param name="dest">The destination object to update. If null, the new instance is created.</param>
    /// <returns>The updated destination object for method chaining, or the new destination instance if either parameter is null.</returns>
    public static global::AlephMapper.Tests.TypeA UpdateTypeA(global::AlephMapper.Tests.CircularPropsSource source, global::AlephMapper.Tests.TypeA dest)
    {
        if (source == null) return dest;
        if (dest == null)
            dest = new global::AlephMapper.Tests.TypeA();
        dest.Name = source?.Name;
        if (dest.B == null)
            dest.B = new global::AlephMapper.Tests.TypeB();
        if (dest.B.A == null)
            dest.B.A = new global::AlephMapper.Tests.TypeA();
        dest.B.A.Name = source?.Name;
        return dest;
    }
#nullable restore
}
