// <auto-generated/>
#nullable enable

using System;
using System.Linq;
using System.Linq.Expressions;

namespace AlephMapper.Tests;

[global::System.CodeDom.Compiler.GeneratedCode("AlephMapper", "0.7.0.0")]
partial class IgnoreMapper
{
    /// <summary>
    /// This is an auto-generated expression companion for <see cref="GetAddress(global::AlephMapper.Tests.SourceDto)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are ignored and treated as regular member access.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.SourceDto, string>> GetAddressExpression() =>
        source => source.BirthInfo.Address ?? "Unknown";

    /// <summary>
    /// This is an auto-generated expression companion for <see cref="HasAddress(global::AlephMapper.Tests.SourceDto)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are ignored and treated as regular member access.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.SourceDto, bool>> HasAddressExpression() =>
        source => source.BirthInfo.Address != null;
}
