// <auto-generated/>
#nullable restore

using AlephMapper;
using System;
using System.Linq;
using System.Linq.Expressions;

namespace Tests;

[global::System.CodeDom.Compiler.GeneratedCode("AlephMapper", "0.7.2.0")]
partial class PersonMapper
{
    /// <summary>
    /// This is an auto-generated adapted mapping method for <see cref="MapPerson(global::Tests.Person)"/>.
    /// </summary>
    public static global::Tests.EmployeeDto MapEmployee(global::Tests.Employee source) =>
        new global::Tests.EmployeeDto
        {
            Id = source.Id,
            Name = source.FirstName + " " + source.LastName,
            Email = source.Email
        };

    /// <summary>
    /// This is an auto-generated adapted expression companion for <see cref="MapPerson(global::Tests.Person)"/>.
    /// </summary>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::Tests.Employee, global::Tests.EmployeeDto>> MapEmployeeExpression() =>
        source => new global::Tests.EmployeeDto
        {
            Id = source.Id,
            Name = source.FirstName + " " + source.LastName,
            Email = source.Email
        };
}
