// <auto-generated/>
#nullable enable

using AlephMapper;
using System;
using System.Linq;
using System.Linq.Expressions;

namespace Tests;

[global::System.CodeDom.Compiler.GeneratedCode("AlephMapper", "0.7.0.0")]
partial class AdaptUpdateMapper
{
    /// <summary>
    /// This is an auto-generated adapted mapping method for <see cref="MapPerson(global::Tests.PersonUpdateDto, string)"/>.
    /// </summary>
    public static global::Tests.Employee MapEmployee(global::Tests.EmployeeUpdateDto source, string prefix) =>
        new global::Tests.Employee
        {
            Name = prefix + source.Name,
            Email = source.Email
        };

    /// <summary>
    /// This is an auto-generated adapted update method for <see cref="MapPerson(global::Tests.PersonUpdateDto, string)"/>.
    /// </summary>
    public static global::Tests.Employee MapEmployee(global::Tests.EmployeeUpdateDto source, string prefix, global::Tests.Employee dest)
    {
        if (source == null) return dest;
        if (dest == null)
            dest = new global::Tests.Employee();
        dest.Name = prefix + source.Name;
        dest.Email = source.Email;
        return dest;
    }
}
