// <auto-generated/>
#nullable enable

using AgileObjects.ReadableExpressions;
using System;
using System.Linq;
using System.Linq.Expressions;

namespace AlephMapper.Tests;

[global::System.CodeDom.Compiler.GeneratedCode("AlephMapper", "0.7.0.0")]
partial class TechDebtPersonMapperRewrite
{
    /// <summary>
    /// This is an auto-generated expression companion for <see cref="ToDto(global::AlephMapper.Tests.TechDebtTestPerson)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are rewritten as explicit null checks for better compatibility.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.TechDebtTestPerson, global::AlephMapper.Tests.TechDebtTestPersonDto>> ToDtoExpression() =>
        person => new global::AlephMapper.Tests.TechDebtTestPersonDto
        {
            Name = person.Name,
            AddressStr = (person.Address != null
                ? (person.Address.FormattedAddress)
                : (string?)null) ?? "No Address"
        };
}
