// <auto-generated/>
#nullable enable

using AgileObjects.ReadableExpressions;
using System;
using System.CodeDom.Compiler;
using System.Linq;
using System.Linq.Expressions;

namespace AlephMapper.Tests;

[GeneratedCode("AlephMapper", "0.7.0.0")]
partial class TechDebtPersonMapperNone
{
}
