// <auto-generated/>
#nullable restore

using System;
using System.Linq;
using System.Linq.Expressions;

namespace AlephMapper.Tests;

[global::System.CodeDom.Compiler.GeneratedCode("AlephMapper", "0.7.2.0")]
partial class EfCoreMapper
{
    /// <summary>
    /// This is an auto-generated expression companion for <see cref="GetPersonComplex(global::AlephMapper.Tests.Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are rewritten as explicit null checks for better compatibility.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.Person, global::AlephMapper.Tests.PersonSummaryDto>> GetPersonComplexExpression() =>
        p => new global::AlephMapper.Tests.PersonSummaryDto
        {
            Id = p.Id,
            Name = p.Name,
            Email = p.Email,
            Age = (p.BirthInfo != null
                ? (p.BirthInfo.Age)
                : (int?)null),
            BirthPlace = (p.BirthInfo != null
                ? (p.BirthInfo.BirthPlace)
                : (string)null) ?? "Unknown",
            BirthAddress = (p.BirthInfo != null
                ? (p.BirthInfo.Address)
                : (string)null) ?? "Not specified",
            HasBirthInfo = p.BirthInfo != null,
            IsAdult = (p.BirthInfo != null
                ? (p.BirthInfo.Age)
                : (int?)null) >= 18,
            AddressCount = p.Addresses.Count,
            OrderCount = p.Orders.Count,
            HasActiveAddress = p.Addresses.Any(a => a.IsActive),
            PersonCategory = p.BirthInfo == null
                ? "Unknown Age"
                : p.BirthInfo.Age < 18
                    ? "Minor"
                    : p.BirthInfo.Age < 65
                        ? "Adult"
                        : "Senior",
            Summary = p.BirthInfo != null
                ? p.Name + " (" + p.BirthInfo.Age + " years old) from " + (p.BirthInfo.BirthPlace ?? "Unknown")
                : p.Name + " (unknown age) from Unknown"
        };

    /// <summary>
    /// This is an auto-generated expression companion for <see cref="GetPersonName(global::AlephMapper.Tests.Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are rewritten as explicit null checks for better compatibility.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.Person, string>> GetPersonNameExpression() =>
        person => person.Name;

    /// <summary>
    /// This is an auto-generated expression companion for <see cref="GetPersonEmail(global::AlephMapper.Tests.Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are rewritten as explicit null checks for better compatibility.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.Person, string>> GetPersonEmailExpression() =>
        person => person.Email;

    /// <summary>
    /// This is an auto-generated expression companion for <see cref="GetPersonAge(global::AlephMapper.Tests.Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are rewritten as explicit null checks for better compatibility.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.Person, int?>> GetPersonAgeExpression() =>
        person => (person.BirthInfo != null
            ? (person.BirthInfo.Age)
            : (int?)null);

    /// <summary>
    /// This is an auto-generated expression companion for <see cref="IsOlderThan30(global::AlephMapper.Tests.Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are rewritten as explicit null checks for better compatibility.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.Person, bool>> IsOlderThan30Expression() =>
        person => (person.BirthInfo != null
            ? (person.BirthInfo.Age)
            : (int?)null) > 30;

    /// <summary>
    /// This is an auto-generated expression companion for <see cref="GetBirthPlace(global::AlephMapper.Tests.Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are rewritten as explicit null checks for better compatibility.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.Person, string>> GetBirthPlaceExpression() =>
        person => (person.BirthInfo != null
            ? (person.BirthInfo.BirthPlace)
            : (string)null) ?? "Unknown";

    /// <summary>
    /// This is an auto-generated expression companion for <see cref="GetBirthAddress(global::AlephMapper.Tests.Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are rewritten as explicit null checks for better compatibility.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.Person, string>> GetBirthAddressExpression() =>
        person => (person.BirthInfo != null
            ? (person.BirthInfo.Address)
            : (string)null) ?? "Not specified";

    /// <summary>
    /// This is an auto-generated expression companion for <see cref="HasBirthInfo(global::AlephMapper.Tests.Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are rewritten as explicit null checks for better compatibility.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.Person, bool>> HasBirthInfoExpression() =>
        person => person.BirthInfo != null;

    /// <summary>
    /// This is an auto-generated expression companion for <see cref="IsAdult(global::AlephMapper.Tests.Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are rewritten as explicit null checks for better compatibility.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.Person, bool>> IsAdultExpression() =>
        person => (person.BirthInfo != null
            ? (person.BirthInfo.Age)
            : (int?)null) >= 18;

    /// <summary>
    /// This is an auto-generated expression companion for <see cref="BornInUkraine(global::AlephMapper.Tests.Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are rewritten as explicit null checks for better compatibility.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.Person, bool>> BornInUkraineExpression() =>
        person => (person.BirthInfo != null
            ? (person.BirthInfo.Address)
            : (string)null) != null && person.BirthInfo.Address.Contains("Ukraine");

    /// <summary>
    /// This is an auto-generated expression companion for <see cref="GetAddressCount(global::AlephMapper.Tests.Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are rewritten as explicit null checks for better compatibility.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.Person, int>> GetAddressCountExpression() =>
        person => person.Addresses.Count;

    /// <summary>
    /// This is an auto-generated expression companion for <see cref="GetOrderCount(global::AlephMapper.Tests.Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are rewritten as explicit null checks for better compatibility.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.Person, int>> GetOrderCountExpression() =>
        person => person.Orders.Count;

    /// <summary>
    /// This is an auto-generated expression companion for <see cref="HasActiveAddress(global::AlephMapper.Tests.Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are rewritten as explicit null checks for better compatibility.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.Person, bool>> HasActiveAddressExpression() =>
        person => person.Addresses.Any(a => a.IsActive);

    /// <summary>
    /// This is an auto-generated expression companion for <see cref="HasCompletedOrders(global::AlephMapper.Tests.Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are rewritten as explicit null checks for better compatibility.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.Person, bool>> HasCompletedOrdersExpression() =>
        person => person.Orders.Any(o => o.IsCompleted);

    /// <summary>
    /// This is an auto-generated expression companion for <see cref="GetTotalOrderAmount(global::AlephMapper.Tests.Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are rewritten as explicit null checks for better compatibility.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.Person, decimal>> GetTotalOrderAmountExpression() =>
        person => person.Orders
            .Where(o => o.IsCompleted)
            .Sum(o => o.Amount);

    /// <summary>
    /// This is an auto-generated expression companion for <see cref="GetPersonSummary(global::AlephMapper.Tests.Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are rewritten as explicit null checks for better compatibility.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.Person, string>> GetPersonSummaryExpression() =>
        person => person.BirthInfo != null
            ? person.Name + " (" + person.BirthInfo.Age + " years old) from " + (person.BirthInfo.BirthPlace ?? "Unknown")
            : person.Name + " (unknown age) from Unknown";

    /// <summary>
    /// This is an auto-generated expression companion for <see cref="LivesInSamePlaceAsBorn(global::AlephMapper.Tests.Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are rewritten as explicit null checks for better compatibility.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.Person, bool>> LivesInSamePlaceAsBornExpression() =>
        person => (person.BirthInfo != null
            ? (person.BirthInfo.BirthPlace)
            : (string)null) != null
            && person.Addresses.Any(a => a.IsActive && a.City == person.BirthInfo.BirthPlace);

    /// <summary>
    /// This is an auto-generated expression companion for <see cref="GetPersonCategory(global::AlephMapper.Tests.Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are rewritten as explicit null checks for better compatibility.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.Person, string>> GetPersonCategoryExpression() =>
        person => person.BirthInfo == null
            ? "Unknown Age"
            : person.BirthInfo.Age < 18
                ? "Minor"
                : person.BirthInfo.Age < 65
                    ? "Adult"
                    : "Senior";

    /// <summary>
    /// This is an auto-generated expression companion for <see cref="IsVipCustomer(global::AlephMapper.Tests.Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are rewritten as explicit null checks for better compatibility.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.Person, bool>> IsVipCustomerExpression() =>
        person => person.Orders
            .Where(o => o.IsCompleted)
            .Sum(o => o.Amount) >= 1000m;
}
