// <auto-generated/>

using System;
using System.Linq;
using System.Linq.Expressions;

namespace AlephMapper.Tests;

[global::System.CodeDom.Compiler.GeneratedCode("AlephMapper", "0.7.0.0")]
partial class EfCoreIgnoreMapper
{
#nullable disable
    /// <summary>
    /// This is an auto-generated expression companion for <see cref="GetPersonName(global::AlephMapper.Tests.Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are ignored and treated as regular member access.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.Person, string>> GetPersonNameExpression() =>
        person => person.Name;
#nullable restore

#nullable disable
    /// <summary>
    /// This is an auto-generated expression companion for <see cref="GetPersonEmail(global::AlephMapper.Tests.Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are ignored and treated as regular member access.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.Person, string>> GetPersonEmailExpression() =>
        person => person.Email;
#nullable restore

#nullable disable
    /// <summary>
    /// This is an auto-generated expression companion for <see cref="GetPersonAge(global::AlephMapper.Tests.Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are ignored and treated as regular member access.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.Person, int?>> GetPersonAgeExpression() =>
        person => person.BirthInfo.Age;
#nullable restore

#nullable disable
    /// <summary>
    /// This is an auto-generated expression companion for <see cref="GetBirthPlace(global::AlephMapper.Tests.Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are ignored and treated as regular member access.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.Person, string>> GetBirthPlaceExpression() =>
        person => person.BirthInfo.BirthPlace ?? "Unknown";
#nullable restore
}
