// <auto-generated/>
#nullable restore

using AlephMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;

namespace AlephMapper.Tests.MethodGroupToEntityList;

[global::System.CodeDom.Compiler.GeneratedCode("AlephMapper", "0.7.1.0")]
partial class PersonMapper
{
    /// <summary>
    /// This is an auto-generated expression companion for <see cref="ToEntity(global::AlephMapper.Tests.MethodGroupToEntityList.PersonDto)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are ignored and treated as regular member access.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.MethodGroupToEntityList.PersonDto, global::AlephMapper.Tests.MethodGroupToEntityList.Person>> ToEntityExpression() =>
        dto => new global::AlephMapper.Tests.MethodGroupToEntityList.Person
        {
            ContactNumbers = dto.PhoneNumbers
                .Select(dto => new global::AlephMapper.Tests.MethodGroupToEntityList.PhoneNumber
                {
                    Number = dto.Number
                })
                .ToList()
        };
}
