// <auto-generated/>

using AgileObjects.ReadableExpressions;
using System;
using System.Linq;
using System.Linq.Expressions;

namespace AlephMapper.Tests;

[global::System.CodeDom.Compiler.GeneratedCode("AlephMapper", "0.7.0.0")]
partial class SimpleObjectMapper
{
#nullable disable
    /// <summary>
    /// This is an auto-generated expression companion for <see cref="MapToDto(global::AlephMapper.Tests.SimpleObject)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are ignored and treated as regular member access.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.SimpleObject, global::AlephMapper.Tests.SimpleDto>> MapToDtoExpression() =>
        so => new global::AlephMapper.Tests.SimpleDto
        {
            Attributes = so.Attributes
                .Select(attr => attr.Name)
                .ToList() ?? new global::System.Collections.Generic.List<string>()
        };
#nullable restore
}
