// <auto-generated/>

using AgileObjects.ReadableExpressions;
using System;
using System.Linq;
using System.Linq.Expressions;

namespace AlephMapper.Tests;

[global::System.CodeDom.Compiler.GeneratedCode("AlephMapper", "0.7.0.0")]
partial class ExtensionTestPersonMapper
{
#nullable disable
    /// <summary>
    /// This is an auto-generated expression companion for <see cref="ToDto(global::AlephMapper.Tests.ExtensionTestPerson)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are ignored and treated as regular member access.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.ExtensionTestPerson, global::AlephMapper.Tests.ExtensionTestPersonDto>> ToDtoExpression() =>
        person => new global::AlephMapper.Tests.ExtensionTestPersonDto
        {
            Id = person.Id,
            Name = person.Name,
            Address = new global::AlephMapper.Tests.ExtensionTestAddressDto
            {
                Street = person.Address.Street,
                City = person.Address.City,
                PostalCode = person.Address.PostalCode,
                FormattedAddress = $"{person.Address.Street}, {person.Address.City} {person.Address.PostalCode}"
            }
        };
#nullable restore
}
