// <auto-generated/>
#nullable restore

using AlephMapper;
using System;
using System.Linq;
using System.Linq.Expressions;

namespace Tests;

[global::System.CodeDom.Compiler.GeneratedCode("AlephMapper", "0.7.2.0")]
partial class NullableDisabledMapper
{
    /// <summary>
    /// This is an auto-generated expression companion for <see cref="GetName(global::Tests.Person)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are rewritten as explicit null checks for better compatibility.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::Tests.Person, string>> GetNameExpression() =>
        person => (person != null
            ? (person.Name)
            : (string)null);
}
