// <auto-generated/>
#nullable restore

using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;

namespace AlephMapper.Tests;

[global::System.CodeDom.Compiler.GeneratedCode("AlephMapper", "0.7.2.0")]
partial class CollectionMapper
{
    /// <summary>
    /// This is an auto-generated expression companion for <see cref="MapToDestWithCollections(global::AlephMapper.Tests.SourceWithCollections)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are ignored and treated as regular member access.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.SourceWithCollections, global::AlephMapper.Tests.DestWithCollections>> MapToDestWithCollectionsExpression() =>
        source => new global::AlephMapper.Tests.DestWithCollections
        {
            Name = source.Name,
            Tags = source.Tags,
            Categories = source.Categories,
            NestedObject = source.NestedObject != null
                ? new global::AlephMapper.Tests.NestedModel
                {
                    Value = source.NestedObject.Value,
                    NestedList = source.NestedObject.NestedList
                }
                : null
        };

    /// <summary>
    /// This is an auto-generated update method for <see cref="MapToDestWithCollections(global::AlephMapper.Tests.SourceWithCollections)"/>.
    /// </summary>
    /// <param name="source">The source object to map values from. If null, no updates are performed.</param>
    /// <param name="dest">The destination object to update. If null, the new instance is created.</param>
    /// <returns>The updated destination object for method chaining, or the new destination instance if either parameter is null.</returns>
    public static global::AlephMapper.Tests.DestWithCollections MapToDestWithCollections(global::AlephMapper.Tests.SourceWithCollections source, global::AlephMapper.Tests.DestWithCollections dest)
    {
        if (source == null) return dest;
        if (dest == null)
            dest = new global::AlephMapper.Tests.DestWithCollections();
        dest.Name = source.Name;
        // Skipping collection property: dest.Tags
        // Skipping collection property: dest.Categories
        if (source.NestedObject != null)
        {
            if (dest.NestedObject == null)
                dest.NestedObject = new global::AlephMapper.Tests.NestedModel();
            dest.NestedObject.Value = source.NestedObject.Value;
            // Skipping collection property: dest.NestedObject.NestedList
        }
        else
        {
            dest.NestedObject = null;
        }
        return dest;
    }

    /// <summary>
    /// This is an auto-generated expression companion for <see cref="MapToDestSimple(global::AlephMapper.Tests.SourceWithCollections)"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null handling strategy: Null-conditional operators are ignored and treated as regular member access.
    /// </para>
    /// </remarks>
    public static global::System.Linq.Expressions.Expression<global::System.Func<global::AlephMapper.Tests.SourceWithCollections, global::AlephMapper.Tests.DestWithCollections>> MapToDestSimpleExpression() =>
        source => new global::AlephMapper.Tests.DestWithCollections
        {
            Name = source.Name,
            NestedObject = source.NestedObject != null
                ? new global::AlephMapper.Tests.NestedModel
                {
                    Value = source.NestedObject.Value
                }
                : null
        };

    /// <summary>
    /// This is an auto-generated update method for <see cref="MapToDestSimple(global::AlephMapper.Tests.SourceWithCollections)"/>.
    /// </summary>
    /// <param name="source">The source object to map values from. If null, no updates are performed.</param>
    /// <param name="dest">The destination object to update. If null, the new instance is created.</param>
    /// <returns>The updated destination object for method chaining, or the new destination instance if either parameter is null.</returns>
    public static global::AlephMapper.Tests.DestWithCollections MapToDestSimple(global::AlephMapper.Tests.SourceWithCollections source, global::AlephMapper.Tests.DestWithCollections dest)
    {
        if (source == null) return dest;
        if (dest == null)
            dest = new global::AlephMapper.Tests.DestWithCollections();
        dest.Name = source.Name;
        if (source.NestedObject != null)
        {
            if (dest.NestedObject == null)
                dest.NestedObject = new global::AlephMapper.Tests.NestedModel();
            dest.NestedObject.Value = source.NestedObject.Value;
        }
        else
        {
            dest.NestedObject = null;
        }
        return dest;
    }
}
